### ISSUE TITLE
issue from today

### ISSUE THREAD

**Issue by platini76** [devbobo/homebridge-arlo#177]
[13/02/2023, 21:08:39] TypeError: Cannot read properties of undefined (reading 'token')
    at Arlo.<anonymous> (/var/lib/homebridge/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:80:32)
    at Request._callback (/var/lib/homebridge/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:415:11)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-arlo/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-arlo/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-arlo/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
[13/02/2023, 21:08:39] Got SIGTERM, shutting down Homebridge...

**Comment by mbial** [comment]
Same issue as of 2 days ago

**Comment by magicman0978** [comment]
same issue i have. Could it be related to 2FA?

**Comment by paisore** [comment]
Same here

**Comment by kMikaZu** [comment]
Is this plugin actually still maintained? Looks dead to me...

**Comment by jmjones-figure** [comment]
I have the same issue.

**Comment by Sladerix** [comment]
same

**Comment by Fluffik3666** [comment]
this is due to 2FA being added to Arlo, this plugin is basically useless now... disappointment
